-- COUNTRIES TABLE
CREATE TABLE IF NOT EXISTS countries (
    country_id INT PRIMARY KEY,
    name VARCHAR(100),
    abbreviation VARCHAR(10),
    flag_link VARCHAR(255)
);

INSERT INTO countries (country_id, name, abbreviation, flag_link) VALUES
(1, 'Afghanistan', 'AF', 'https://www.worldometers.info/img/flags/small/tn_af-flag.gif'),
(2, 'Albania', 'AL', 'https://www.worldometers.info/img/flags/small/tn_al-flag.gif'),
(3, 'Algeria', 'DZ', 'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif'),
(4, 'Andorra', 'AD', 'https://www.worldometers.info/img/flags/small/tn_ad-flag.gif'),
(5, 'Angola', 'AO', 'https://www.worldometers.info/img/flags/small/tn_ao-flag.gif'),
(6, 'Antigua and Barbuda', 'AG', 'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif'),
(7, 'Argentina', 'AR', 'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif'),
(8, 'Armenia', 'AM', 'https://www.worldometers.info/img/flags/small/tn_am-flag.gif'),
(9, 'Australia', 'AU', 'https://www.worldometers.info/img/flags/small/tn_au-flag.gif'),
(10, 'Austria', 'AT', 'https://www.worldometers.info/img/flags/small/tn_at-flag.gif'),
(11, 'Azerbaijan', 'AZ', 'https://www.worldometers.info/img/flags/small/tn_az-flag.gif'),
(12, 'Bahamas', 'BS', 'https://www.worldometers.info/img/flags/small/tn_bs-flag.gif'),
(13, 'Bahrain', 'BH', 'https://www.worldometers.info/img/flags/small/tn_bh-flag.gif'),
(14, 'Bangladesh', 'BD', 'https://www.worldometers.info/img/flags/small/tn_bd-flag.gif'),
(15, 'Barbados', 'BB', 'https://www.worldometers.info/img/flags/small/tn_bb-flag.gif'),
(16, 'Belarus', 'BY', 'https://www.worldometers.info/img/flags/small/tn_by-flag.gif'),
(17, 'Belgium', 'BE', 'https://www.worldometers.info/img/flags/small/tn_be-flag.gif'),
(18, 'Belize', 'BZ', 'https://www.worldometers.info/img/flags/small/tn_bz-flag.gif'),
(19, 'Benin', 'BJ', 'https://www.worldometers.info/img/flags/small/tn_bj-flag.gif'),
(20, 'Bhutan', 'BT', 'https://www.worldometers.info/img/flags/small/tn_bt-flag.gif'),
(21, 'Bolivia', 'BO', 'https://www.worldometers.info/img/flags/small/tn_bo-flag.gif'),
(22, 'Bosnia and Herzegovina', 'BA', 'https://www.worldometers.info/img/flags/small/tn_ba-flag.gif'),
(23, 'Botswana', 'BW', 'https://www.worldometers.info/img/flags/small/tn_bw-flag.gif'),
(24, 'Brazil', 'BR', 'https://www.worldometers.info/img/flags/small/tn_br-flag.gif'),
(25, 'Brunei', 'BN', 'https://www.worldometers.info/img/flags/small/tn_bn-flag.gif'),
(26, 'Bulgaria', 'BG', 'https://www.worldometers.info/img/flags/small/tn_bg-flag.gif'),
(27, 'Burkina Faso', 'BF', 'https://www.worldometers.info/img/flags/small/tn_bf-flag.gif'),
(28, 'Burundi', 'BI', 'https://www.worldometers.info/img/flags/small/tn_bi-flag.gif'),
(29, 'Cabo Verde', 'CV', 'https://www.worldometers.info/img/flags/small/tn_cv-flag.gif'),
(30, 'Cambodia', 'KH', 'https://www.worldometers.info/img/flags/small/tn_kh-flag.gif'),
(31, 'Cameroon', 'CM', 'https://www.worldometers.info/img/flags/small/tn_cm-flag.gif'),
(32, 'Canada', 'CA', 'https://www.worldometers.info/img/flags/small/tn_ca-flag.gif'),
(33, 'Central African Republic', 'CF', 'https://www.worldometers.info/img/flags/small/tn_cf-flag.gif'),
(34, 'Chad', 'TD', 'https://www.worldometers.info/img/flags/small/tn_td-flag.gif'),
(35, 'Chile', 'CL', 'https://www.worldometers.info/img/flags/small/tn_cl-flag.gif'),
(36, 'China', 'CN', 'https://www.worldometers.info/img/flags/small/tn_ch-flag.gif'),
(37, 'Colombia', 'CO', 'https://www.worldometers.info/img/flags/small/tn_co-flag.gif'),
(38, 'Comoros', 'KM', 'https://www.worldometers.info/img/flags/small/tn_km-flag.gif'),
(39, 'Congo (Congo-Brazzaville)', 'CG', 'https://www.worldometers.info/img/flags/small/tn_cg-flag.gif'),
(40, 'Congo (Democratic Republic)', 'CD', 'https://www.worldometers.info/img/flags/small/tn_cd-flag.gif'),
(41, 'Costa Rica', 'CR', 'https://www.worldometers.info/img/flags/small/tn_cr-flag.gif'),
(42, 'Croatia', 'HR', 'https://www.worldometers.info/img/flags/small/tn_hr-flag.gif'),
(43, 'Cuba', 'CU', 'https://www.worldometers.info/img/flags/small/tn_cu-flag.gif'),
(44, 'Cyprus', 'CY', 'https://www.worldometers.info/img/flags/small/tn_cy-flag.gif'),
(45, 'Czech Republic', 'CZ', 'https://www.worldometers.info/img/flags/small/tn_cz-flag.gif'),
(46, 'Denmark', 'DK', 'https://www.worldometers.info/img/flags/small/tn_da-flag.gif'),
(47, 'Djibouti', 'DJ', 'https://www.worldometers.info/img/flags/small/tn_dj-flag.gif'),
(48, 'Dominica', 'DM', 'https://www.worldometers.info/img/flags/small/tn_dm-flag.gif'),
(49, 'Dominican Republic', 'DO', 'https://www.worldometers.info/img/flags/small/tn_dr-flag.gif'),
(50, 'Ecuador', 'EC', 'https://www.worldometers.info/img/flags/small/tn_ec-flag.gif'),
(51, 'Egypt', 'EG', 'https://www.worldometers.info/img/flags/small/tn_eg-flag.gif'),
(52, 'El Salvador', 'SV', 'https://www.worldometers.info/img/flags/small/tn_es-flag.gif'),
(53, 'Equatorial Guinea', 'GQ', 'https://www.worldometers.info/img/flags/small/tn_gq-flag.gif'),
(54, 'Eritrea', 'ER', 'https://www.worldometers.info/img/flags/small/tn_er-flag.gif'),
(55, 'Estonia', 'EE', 'https://www.worldometers.info/img/flags/small/tn_ee-flag.gif'),
(56, 'Eswatini', 'SZ', 'https://www.worldometers.info/img/flags/small/tn_wz-flag.gif'),
(57, 'Ethiopia', 'ET', 'https://www.worldometers.info/img/flags/small/tn_et-flag.gif'),
(58, 'Fiji', 'FJ', 'https://www.worldometers.info/img/flags/small/tn_fj-flag.gif'),
(59, 'Finland', 'FI', 'https://www.worldometers.info/img/flags/small/tn_fi-flag.gif'),
(60, 'France', 'FR', 'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif'),
(61, 'Gabon', 'GA', 'https://www.worldometers.info/img/flags/small/tn_ga-flag.gif'),
(62, 'Gambia', 'GM', 'https://www.worldometers.info/img/flags/small/tn_ga-flag.gif'),
(63, 'Georgia', 'GE', 'https://www.worldometers.info/img/flags/small/tn_gg-flag.gif'),
(64, 'Germany', 'DE', 'https://www.worldometers.info/img/flags/small/tn_gm-flag.gif'),
(65, 'Ghana', 'GH', 'https://www.worldometers.info/img/flags/small/tn_gh-flag.gif'),
(66, 'Greece', 'GR', 'https://www.worldometers.info/img/flags/small/tn_gr-flag.gif'),
(67, 'Grenada', 'GD', 'https://www.worldometers.info/img/flags/small/tn_gj-flag.gif'),
(68, 'Guatemala', 'GT', 'https://www.worldometers.info/img/flags/small/tn_gt-flag.gif'),
(69, 'Guinea', 'GN', 'https://www.worldometers.info/img/flags/small/tn_gv-flag.gif'),
(70, 'Guinea-Bissau', 'GW', 'https://www.worldometers.info/img/flags/small/tn_pu-flag.gif'),
(71, 'Guyana', 'GY', 'https://www.worldometers.info/img/flags/small/tn_gy-flag.gif'),
(72, 'Haiti', 'HT', 'https://www.worldometers.info/img/flags/small/tn_ha-flag.gif'),
(73, 'Honduras', 'HN', 'https://www.worldometers.info/img/flags/small/tn_ho-flag.gif'),
(74, 'Hungary', 'HU', 'https://www.worldometers.info/img/flags/small/tn_hu-flag.gif'),
(75, 'Iceland', 'IS', 'https://www.worldometers.info/img/flags/small/tn_ic-flag.gif'),
(76, 'India', 'IN', 'https://www.worldometers.info/img/flags/small/tn_in-flag.gif'),
(77, 'Indonesia', 'ID', 'https://www.worldometers.info/img/flags/small/tn_id-flag.gif'),
(78, 'Iran', 'IR', 'https://www.worldometers.info/img/flags/small/tn_ir-flag.gif'),
(79, 'Iraq', 'IQ', 'https://www.worldometers.info/img/flags/small/tn_iz-flag.gif'),
(80, 'Ireland', 'IE', 'https://www.worldometers.info/img/flags/small/tn_ei-flag.gif'),
(81, 'Israel', 'IL', 'https://www.worldometers.info/img/flags/small/tn_is-flag.gif'),
(82, 'Italy', 'IT', 'https://www.worldometers.info/img/flags/small/tn_it-flag.gif'),
(83, 'Jamaica', 'JM', 'https://www.worldometers.info/img/flags/small/tn_jm-flag.gif'),
(84, 'Japan', 'JP', 'https://www.worldometers.info/img/flags/small/tn_ja-flag.gif'),
(85, 'Jordan', 'JO', 'https://www.worldometers.info/img/flags/small/tn_jo-flag.gif'),
(86, 'Kazakhstan', 'KZ', 'https://www.worldometers.info/img/flags/small/tn_kz-flag.gif'),
(87, 'Kenya', 'KE', 'https://www.worldometers.info/img/flags/small/tn_ke-flag.gif'),
(88, 'Kiribati', 'KI', 'https://www.worldometers.info/img/flags/small/tn_kr-flag.gif'),
(89, 'Korea (North)', 'KP', 'https://www.worldometers.info/img/flags/small/tn_kn-flag.gif'),
(90, 'Korea (South)', 'KR', 'https://www.worldometers.info/img/flags/small/tn_ks-flag.gif'),
(91, 'Kuwait', 'KW', 'https://www.worldometers.info/img/flags/small/tn_ku-flag.gif'),
(92, 'Kyrgyzstan', 'KG', 'https://www.worldometers.info/img/flags/small/tn_kg-flag.gif'),
(93, 'Laos', 'LA', 'https://www.worldometers.info/img/flags/small/tn_la-flag.gif'),
(94, 'Latvia', 'LV', 'https://www.worldometers.info/img/flags/small/tn_lg-flag.gif'),
(95, 'Lebanon', 'LB', 'https://www.worldometers.info/img/flags/small/tn_le-flag.gif'),
(96, 'Lesotho', 'LS', 'https://www.worldometers.info/img/flags/small/tn_lt-flag.gif'),
(97, 'Liberia', 'LR', 'https://www.worldometers.info/img/flags/small/tn_li-flag.gif'),
(98, 'Libya', 'LY', 'https://www.worldometers.info/img/flags/small/tn_ly-flag.gif'),
(99, 'Liechtenstein', 'LI', 'https://www.worldometers.info/img/flags/small/tn_ls-flag.gif'),
(100, 'Lithuania', 'LT', 'https://www.worldometers.info/img/flags/small/tn_lh-flag.gif'),
(101, 'Luxembourg', 'LU', 'https://www.worldometers.info/img/flags/small/tn_lu-flag.gif'),
(102, 'Madagascar', 'MG', 'https://www.worldometers.info/img/flags/small/tn_ma-flag.gif'),
(103, 'Malawi', 'MW', 'https://www.worldometers.info/img/flags/small/tn_mi-flag.gif'),
(104, 'Malaysia', 'MY', 'https://www.worldometers.info/img/flags/small/tn_my-flag.gif'),
(105, 'Maldives', 'MV', 'https://www.worldometers.info/img/flags/small/tn_mv-flag.gif'),
(106, 'Mali', 'ML', 'https://www.worldometers.info/img/flags/small/tn_ml-flag.gif'),
(107, 'Malta', 'MT', 'https://www.worldometers.info/img/flags/small/tn_mt-flag.gif'),
(108, 'Marshall Islands', 'MH', 'https://www.worldometers.info/img/flags/small/tn_rm-flag.gif'),
(109, 'Mauritania', 'MR', 'https://www.worldometers.info/img/flags/small/tn_mr-flag.gif'),
(110, 'Mauritius', 'MU', 'https://www.worldometers.info/img/flags/small/tn_mp-flag.gif'),
(111, 'Mexico', 'MX', 'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif'),
(112, 'Micronesia', 'FM', 'https://www.worldometers.info/img/flags/small/tn_fm-flag.gif'),
(113, 'Moldova', 'MD', 'https://www.worldometers.info/img/flags/small/tn_md-flag.gif'),
(114, 'Monaco', 'MC', 'https://www.worldometers.info/img/flags/small/tn_mn-flag.gif'),
(115, 'Mongolia', 'MN', 'https://www.worldometers.info/img/flags/small/tn_mg-flag.gif'),
(116, 'Montenegro', 'ME', 'https://www.worldometers.info/img/flags/small/tn_mj-flag.gif'),
(117, 'Morocco', 'MA', 'https://www.worldometers.info/img/flags/small/tn_mo-flag.gif'),
(118, 'Mozambique', 'MZ', 'https://www.worldometers.info/img/flags/small/tn_mz-flag.gif'),
(119, 'Myanmar', 'MM', 'https://www.worldometers.info/img/flags/small/tn_bm-flag.gif'),
(120, 'Namibia', 'NA', 'https://www.worldometers.info/img/flags/small/tn_wa-flag.gif'),
(121, 'Nauru', 'NR', 'https://www.worldometers.info/img/flags/small/tn_nr-flag.gif'),
(122, 'Nepal', 'NP', 'https://www.worldometers.info/img/flags/small/tn_np-flag.gif'),
(123, 'Netherlands', 'NL', 'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif'),
(124, 'New Zealand', 'NZ', 'https://www.worldometers.info/img/flags/small/tn_nz-flag.gif'),
(125, 'Nicaragua', 'NI', 'https://www.worldometers.info/img/flags/small/tn_nu-flag.gif'),
(126, 'Niger', 'NE', 'https://www.worldometers.info/img/flags/small/tn_ng-flag.gif'),
(127, 'Nigeria', 'NG', 'https://www.worldometers.info/img/flags/small/tn_ni-flag.gif'),
(128, 'North Macedonia', 'MK', 'https://www.worldometers.info/img/flags/small/tn_mk-flag.gif'),
(129, 'Norway', 'NO', 'https://www.worldometers.info/img/flags/small/tn_no-flag.gif'),
(130, 'Oman', 'OM', 'https://www.worldometers.info/img/flags/small/tn_mu-flag.gif'),
(131, 'Pakistan', 'PK', 'https://www.worldometers.info/img/flags/small/tn_pk-flag.gif'),
(132, 'Palau', 'PW', 'https://www.worldometers.info/img/flags/small/tn_ps-flag.gif'),
(133, 'Panama', 'PA', 'https://www.worldometers.info/img/flags/small/tn_pm-flag.gif'),
(134, 'Papua New Guinea', 'PG', 'https://www.worldometers.info/img/flags/small/tn_pp-flag.gif'),
(135, 'Paraguay', 'PY', 'https://www.worldometers.info/img/flags/small/tn_pa-flag.gif'),
(136, 'Peru', 'PE', 'https://www.worldometers.info/img/flags/small/tn_pe-flag.gif'),
(137, 'Philippines', 'PH', 'https://www.worldometers.info/img/flags/small/tn_rp-flag.gif'),
(138, 'Poland', 'PL', 'https://www.worldometers.info/img/flags/small/tn_pl-flag.gif'),
(139, 'Portugal', 'PT', 'https://www.worldometers.info/img/flags/small/tn_po-flag.gif'),
(140, 'Qatar', 'QA', 'https://www.worldometers.info/img/flags/small/tn_qa-flag.gif'),
(141, 'Romania', 'RO', 'https://www.worldometers.info/img/flags/small/tn_ro-flag.gif'),
(142, 'Russia', 'RU', 'https://www.worldometers.info/img/flags/small/tn_rs-flag.gif'),
(143, 'Rwanda', 'RW', 'https://www.worldometers.info/img/flags/small/tn_rw-flag.gif'),
(144, 'Saint Kitts and Nevis', 'KN', 'https://www.worldometers.info/img/flags/small/tn_sc-flag.gif'),
(145, 'Saint Lucia', 'LC', 'https://www.worldometers.info/img/flags/small/tn_st-flag.gif'),
(146, 'Saint Vincent and the Grenadines', 'VC', 'https://www.worldometers.info/img/flags/small/tn_vc-flag.gif'),
(147, 'Samoa', 'WS', 'https://www.worldometers.info/img/flags/small/tn_ws-flag.gif'),
(148, 'San Marino', 'SM', 'https://www.worldometers.info/img/flags/small/tn_sm-flag.gif'),
(149, 'Sao Tome and Principe', 'ST', 'https://www.worldometers.info/img/flags/small/tn_tp-flag.gif'),
(150, 'Saudi Arabia', 'SA', 'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif'),
(151, 'Senegal', 'SN', 'https://www.worldometers.info/img/flags/small/tn_sg-flag.gif'),
(152, 'Serbia', 'RS', 'https://www.worldometers.info/img/flags/small/tn_ri-flag.gif'),
(153, 'Seychelles', 'SC', 'https://www.worldometers.info/img/flags/small/tn_se-flag.gif'),
(154, 'Sierra Leone', 'SL', 'https://www.worldometers.info/img/flags/small/tn_sl-flag.gif'),
(155, 'Singapore', 'SG', 'https://www.worldometers.info/img/flags/small/tn_sn-flag.gif'),
(156, 'Slovakia', 'SK', 'https://www.worldometers.info/img/flags/small/tn_lo-flag.gif'),
(157, 'Slovenia', 'SI', 'https://www.worldometers.info/img/flags/small/tn_si-flag.gif'),
(158, 'Solomon Islands', 'SB', 'https://www.worldometers.info/img/flags/small/tn_bp-flag.gif'),
(159, 'Somalia', 'SO', 'https://www.worldometers.info/img/flags/small/tn_so-flag.gif'),
(160, 'South Africa', 'ZA', 'https://www.worldometers.info/img/flags/small/tn_sf-flag.gif'),
(161, 'South Sudan', 'SS', 'https://www.worldometers.info/img/flags/small/tn_od-flag.gif'),
(162, 'Spain', 'ES', 'https://www.worldometers.info/img/flags/small/tn_sp-flag.gif'),
(163, 'Sri Lanka', 'LK', 'https://www.worldometers.info/img/flags/small/tn_ce-flag.gif'),
(164, 'Sudan', 'SD', 'https://www.worldometers.info/img/flags/small/tn_su-flag.gif'),
(165, 'Suriname', 'SR', 'https://www.worldometers.info/img/flags/small/tn_ns-flag.gif'),
(166, 'Sweden', 'SE', 'https://www.worldometers.info/img/flags/small/tn_sw-flag.gif'),
(167, 'Switzerland', 'CH', 'https://www.worldometers.info/img/flags/small/tn_sz-flag.gif'),
(168, 'Syria', 'SY', 'https://www.worldometers.info/img/flags/small/tn_sy-flag.gif'),
(169, 'Taiwan', 'TW', 'https://www.worldometers.info/img/flags/small/tn_tw-flag.gif'),
(170, 'Tajikistan', 'TJ', 'https://www.worldometers.info/img/flags/small/tn_ti-flag.gif'),
(171, 'Tanzania', 'TZ', 'https://www.worldometers.info/img/flags/small/tn_tz-flag.gif'),
(172, 'Thailand', 'TH', 'https://www.worldometers.info/img/flags/small/tn_th-flag.gif'),
(173, 'Togo', 'TG', 'https://www.worldometers.info/img/flags/small/tn_to-flag.gif'),
(174, 'Tonga', 'TO', 'https://www.worldometers.info/img/flags/small/tn_tn-flag.gif'),
(175, 'Trinidad and Tobago', 'TT', 'https://www.worldometers.info/img/flags/small/tn_td-flag.gif'),
(176, 'Tunisia', 'TN', 'https://www.worldometers.info/img/flags/small/tn_ts-flag.gif'),
(177, 'Turkey', 'TR', 'https://www.worldometers.info/img/flags/small/tn_tu-flag.gif'),
(178, 'Turkmenistan', 'TM', 'https://www.worldometers.info/img/flags/small/tn_tx-flag.gif'),
(179, 'Tuvalu', 'TV', 'https://www.worldometers.info/img/flags/small/tn_tv-flag.gif'),
(180, 'Uganda', 'UG', 'https://www.worldometers.info/img/flags/small/tn_ug-flag.gif'),
(181, 'Ukraine', 'UA', 'https://www.worldometers.info/img/flags/small/tn_up-flag.gif'),
(182, 'United Arab Emirates', 'AE', 'https://www.worldometers.info/img/flags/small/tn_ae-flag.gif'),
(183, 'United Kingdom', 'GB', 'https://www.worldometers.info/img/flags/small/tn_uk-flag.gif'),
(184, 'United States', 'US', 'https://www.worldometers.info/img/flags/small/tn_us-flag.gif'),
(185, 'Uruguay', 'UY', 'https://www.worldometers.info/img/flags/small/tn_uy-flag.gif'),
(186, 'Uzbekistan', 'UZ', 'https://www.worldometers.info/img/flags/small/tn_uz-flag.gif'),
(187, 'Vanuatu', 'VU', 'https://www.worldometers.info/img/flags/small/tn_ve-flag.gif'),
(188, 'Vatican City', 'VA', 'https://www.worldometers.info/img/flags/small/tn_vt-flag.gif'),
(189, 'Venezuela', 'VE', 'https://www.worldometers.info/img/flags/small/tn_ve-flag.gif'),
(190, 'Vietnam', 'VN', 'https://www.worldometers.info/img/flags/small/tn_vm-flag.gif'),
(191, 'Yemen', 'YE', 'https://www.worldometers.info/img/flags/small/tn_ym-flag.gif'),
(192, 'Zambia', 'ZM', 'https://www.worldometers.info/img/flags/small/tn_za-flag.gif'),
(193, 'Zimbabwe', 'ZW', 'https://www.worldometers.info/img/flags/small/tn_zi-flag.gif'),
(194, 'Scotland', 'SCO', 'https://en.wikipedia.org/wiki/Scotland#/media/File:Flag_of_Scotland.svg'),
(195, 'Puerto Rico', 'PR', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg'),
(196, 'US Virgin Islands', 'USVI', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg');

SELECT * FROM countries limit 5;
