-- COUNTRIES TABLE
CREATE TABLE IF NOT EXISTS countries (
    country_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100),
    abbreviation VARCHAR(10),
    flag_link VARCHAR(255)
);

INSERT INTO countries (name, abbreviation, flag_link) VALUES
( 'Afghanistan', 'AF', 'https://www.worldometers.info/img/flags/small/tn_af-flag.gif'),
( 'Albania', 'AL', 'https://www.worldometers.info/img/flags/small/tn_al-flag.gif'),
( 'Algeria', 'DZ', 'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif'),
( 'Andorra', 'AD', 'https://www.worldometers.info/img/flags/small/tn_ad-flag.gif'),
( 'Angola', 'AO', 'https://www.worldometers.info/img/flags/small/tn_ao-flag.gif'),
( 'Antigua and Barbuda', 'AG', 'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif'),
( 'Argentina', 'AR', 'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif'),
( 'Armenia', 'AM', 'https://www.worldometers.info/img/flags/small/tn_am-flag.gif'),
( 'Australia', 'AU', 'https://www.worldometers.info/img/flags/small/tn_au-flag.gif'),
( 'Austria', 'AT', 'https://www.worldometers.info/img/flags/small/tn_at-flag.gif'),
( 'Azerbaijan', 'AZ', 'https://www.worldometers.info/img/flags/small/tn_az-flag.gif'),
( 'Bahamas', 'BS', 'https://www.worldometers.info/img/flags/small/tn_bs-flag.gif'),
( 'Bahrain', 'BH', 'https://www.worldometers.info/img/flags/small/tn_bh-flag.gif'),
( 'Bangladesh', 'BD', 'https://www.worldometers.info/img/flags/small/tn_bd-flag.gif'),
( 'Barbados', 'BB', 'https://www.worldometers.info/img/flags/small/tn_bb-flag.gif'),
( 'Belarus', 'BY', 'https://www.worldometers.info/img/flags/small/tn_by-flag.gif'),
( 'Belgium', 'BE', 'https://www.worldometers.info/img/flags/small/tn_be-flag.gif'),
( 'Belize', 'BZ', 'https://www.worldometers.info/img/flags/small/tn_bz-flag.gif'),
( 'Benin', 'BJ', 'https://www.worldometers.info/img/flags/small/tn_bj-flag.gif'),
( 'Bhutan', 'BT', 'https://www.worldometers.info/img/flags/small/tn_bt-flag.gif'),
( 'Bolivia', 'BO', 'https://www.worldometers.info/img/flags/small/tn_bo-flag.gif'),
( 'Bosnia and Herzegovina', 'BA', 'https://www.worldometers.info/img/flags/small/tn_ba-flag.gif'),
( 'Botswana', 'BW', 'https://www.worldometers.info/img/flags/small/tn_bw-flag.gif'),
( 'Brazil', 'BR', 'https://www.worldometers.info/img/flags/small/tn_br-flag.gif'),
( 'Brunei', 'BN', 'https://www.worldometers.info/img/flags/small/tn_bn-flag.gif'),
( 'Bulgaria', 'BG', 'https://www.worldometers.info/img/flags/small/tn_bg-flag.gif'),
( 'Burkina Faso', 'BF', 'https://www.worldometers.info/img/flags/small/tn_bf-flag.gif'),
( 'Burundi', 'BI', 'https://www.worldometers.info/img/flags/small/tn_bi-flag.gif'),
( 'Cabo Verde', 'CV', 'https://www.worldometers.info/img/flags/small/tn_cv-flag.gif'),
( 'Cambodia', 'KH', 'https://www.worldometers.info/img/flags/small/tn_kh-flag.gif'),
( 'Cameroon', 'CM', 'https://www.worldometers.info/img/flags/small/tn_cm-flag.gif'),
( 'Canada', 'CA', 'https://www.worldometers.info/img/flags/small/tn_ca-flag.gif'),
( 'Central African Republic', 'CF', 'https://www.worldometers.info/img/flags/small/tn_cf-flag.gif'),
( 'Chad', 'TD', 'https://www.worldometers.info/img/flags/small/tn_td-flag.gif'),
( 'Chile', 'CL', 'https://www.worldometers.info/img/flags/small/tn_cl-flag.gif'),
( 'China', 'CN', 'https://www.worldometers.info/img/flags/small/tn_ch-flag.gif'),
( 'Colombia', 'CO', 'https://www.worldometers.info/img/flags/small/tn_co-flag.gif'),
( 'Comoros', 'KM', 'https://www.worldometers.info/img/flags/small/tn_km-flag.gif'),
( 'Congo (Congo-Brazzaville)', 'CG', 'https://www.worldometers.info/img/flags/small/tn_cg-flag.gif'),
( 'Congo (Democratic Republic)', 'CD', 'https://www.worldometers.info/img/flags/small/tn_cd-flag.gif'),
( 'Costa Rica', 'CR', 'https://www.worldometers.info/img/flags/small/tn_cr-flag.gif'),
( 'Croatia', 'HR', 'https://www.worldometers.info/img/flags/small/tn_hr-flag.gif'),
( 'Cuba', 'CU', 'https://www.worldometers.info/img/flags/small/tn_cu-flag.gif'),
( 'Cyprus', 'CY', 'https://www.worldometers.info/img/flags/small/tn_cy-flag.gif'),
( 'Czech Republic', 'CZ', 'https://www.worldometers.info/img/flags/small/tn_cz-flag.gif'),
( 'Denmark', 'DK', 'https://www.worldometers.info/img/flags/small/tn_da-flag.gif'),
( 'Djibouti', 'DJ', 'https://www.worldometers.info/img/flags/small/tn_dj-flag.gif'),
( 'Dominica', 'DM', 'https://www.worldometers.info/img/flags/small/tn_dm-flag.gif'),
( 'Dominican Republic', 'DO', 'https://www.worldometers.info/img/flags/small/tn_dr-flag.gif'),
( 'Ecuador', 'EC', 'https://www.worldometers.info/img/flags/small/tn_ec-flag.gif'),
( 'Egypt', 'EG', 'https://www.worldometers.info/img/flags/small/tn_eg-flag.gif'),
( 'El Salvador', 'SV', 'https://www.worldometers.info/img/flags/small/tn_es-flag.gif'),
( 'Equatorial Guinea', 'GQ', 'https://www.worldometers.info/img/flags/small/tn_gq-flag.gif'),
( 'Eritrea', 'ER', 'https://www.worldometers.info/img/flags/small/tn_er-flag.gif'),
( 'Estonia', 'EE', 'https://www.worldometers.info/img/flags/small/tn_ee-flag.gif'),
( 'Eswatini', 'SZ', 'https://www.worldometers.info/img/flags/small/tn_wz-flag.gif'),
( 'Ethiopia', 'ET', 'https://www.worldometers.info/img/flags/small/tn_et-flag.gif'),
( 'Fiji', 'FJ', 'https://www.worldometers.info/img/flags/small/tn_fj-flag.gif'),
( 'Finland', 'FI', 'https://www.worldometers.info/img/flags/small/tn_fi-flag.gif'),
( 'France', 'FR', 'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif'),
( 'Gabon', 'GA', 'https://www.worldometers.info/img/flags/small/tn_ga-flag.gif'),
( 'Gambia', 'GM', 'https://www.worldometers.info/img/flags/small/tn_ga-flag.gif'),
( 'Georgia', 'GE', 'https://www.worldometers.info/img/flags/small/tn_gg-flag.gif'),
( 'Germany', 'DE', 'https://www.worldometers.info/img/flags/small/tn_gm-flag.gif'),
( 'Ghana', 'GH', 'https://www.worldometers.info/img/flags/small/tn_gh-flag.gif'),
( 'Greece', 'GR', 'https://www.worldometers.info/img/flags/small/tn_gr-flag.gif'),
( 'Grenada', 'GD', 'https://www.worldometers.info/img/flags/small/tn_gj-flag.gif'),
( 'Guatemala', 'GT', 'https://www.worldometers.info/img/flags/small/tn_gt-flag.gif'),
( 'Guinea', 'GN', 'https://www.worldometers.info/img/flags/small/tn_gv-flag.gif'),
( 'Guinea-Bissau', 'GW', 'https://www.worldometers.info/img/flags/small/tn_pu-flag.gif'),
( 'Guyana', 'GY', 'https://www.worldometers.info/img/flags/small/tn_gy-flag.gif'),
( 'Haiti', 'HT', 'https://www.worldometers.info/img/flags/small/tn_ha-flag.gif'),
( 'Honduras', 'HN', 'https://www.worldometers.info/img/flags/small/tn_ho-flag.gif'),
( 'Hungary', 'HU', 'https://www.worldometers.info/img/flags/small/tn_hu-flag.gif'),
( 'Iceland', 'IS', 'https://www.worldometers.info/img/flags/small/tn_ic-flag.gif'),
( 'India', 'IN', 'https://www.worldometers.info/img/flags/small/tn_in-flag.gif'),
( 'Indonesia', 'ID', 'https://www.worldometers.info/img/flags/small/tn_id-flag.gif'),
( 'Iran', 'IR', 'https://www.worldometers.info/img/flags/small/tn_ir-flag.gif'),
( 'Iraq', 'IQ', 'https://www.worldometers.info/img/flags/small/tn_iz-flag.gif'),
( 'Ireland', 'IE', 'https://www.worldometers.info/img/flags/small/tn_ei-flag.gif'),
( 'Israel', 'IL', 'https://www.worldometers.info/img/flags/small/tn_is-flag.gif'),
( 'Italy', 'IT', 'https://www.worldometers.info/img/flags/small/tn_it-flag.gif'),
( 'Jamaica', 'JM', 'https://www.worldometers.info/img/flags/small/tn_jm-flag.gif'),
( 'Japan', 'JP', 'https://www.worldometers.info/img/flags/small/tn_ja-flag.gif'),
( 'Jordan', 'JO', 'https://www.worldometers.info/img/flags/small/tn_jo-flag.gif'),
( 'Kazakhstan', 'KZ', 'https://www.worldometers.info/img/flags/small/tn_kz-flag.gif'),
( 'Kenya', 'KE', 'https://www.worldometers.info/img/flags/small/tn_ke-flag.gif'),
( 'Kiribati', 'KI', 'https://www.worldometers.info/img/flags/small/tn_kr-flag.gif'),
( 'Korea (North)', 'KP', 'https://www.worldometers.info/img/flags/small/tn_kn-flag.gif'),
( 'Korea (South)', 'KR', 'https://www.worldometers.info/img/flags/small/tn_ks-flag.gif'),
( 'Kuwait', 'KW', 'https://www.worldometers.info/img/flags/small/tn_ku-flag.gif'),
( 'Kyrgyzstan', 'KG', 'https://www.worldometers.info/img/flags/small/tn_kg-flag.gif'),
( 'Laos', 'LA', 'https://www.worldometers.info/img/flags/small/tn_la-flag.gif'),
( 'Latvia', 'LV', 'https://www.worldometers.info/img/flags/small/tn_lg-flag.gif'),
( 'Lebanon', 'LB', 'https://www.worldometers.info/img/flags/small/tn_le-flag.gif'),
( 'Lesotho', 'LS', 'https://www.worldometers.info/img/flags/small/tn_lt-flag.gif'),
( 'Liberia', 'LR', 'https://www.worldometers.info/img/flags/small/tn_li-flag.gif'),
( 'Libya', 'LY', 'https://www.worldometers.info/img/flags/small/tn_ly-flag.gif'),
( 'Liechtenstein', 'LI', 'https://www.worldometers.info/img/flags/small/tn_ls-flag.gif'),
( 'Lithuania', 'LT', 'https://www.worldometers.info/img/flags/small/tn_lh-flag.gif'),
( 'Luxembourg', 'LU', 'https://www.worldometers.info/img/flags/small/tn_lu-flag.gif'),
( 'Madagascar', 'MG', 'https://www.worldometers.info/img/flags/small/tn_ma-flag.gif'),
( 'Malawi', 'MW', 'https://www.worldometers.info/img/flags/small/tn_mi-flag.gif'),
( 'Malaysia', 'MY', 'https://www.worldometers.info/img/flags/small/tn_my-flag.gif'),
( 'Maldives', 'MV', 'https://www.worldometers.info/img/flags/small/tn_mv-flag.gif'),
( 'Mali', 'ML', 'https://www.worldometers.info/img/flags/small/tn_ml-flag.gif'),
( 'Malta', 'MT', 'https://www.worldometers.info/img/flags/small/tn_mt-flag.gif'),
( 'Marshall Islands', 'MH', 'https://www.worldometers.info/img/flags/small/tn_rm-flag.gif'),
( 'Mauritania', 'MR', 'https://www.worldometers.info/img/flags/small/tn_mr-flag.gif'),
( 'Mauritius', 'MU', 'https://www.worldometers.info/img/flags/small/tn_mp-flag.gif'),
( 'Mexico', 'MX', 'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif'),
( 'Micronesia', 'FM', 'https://www.worldometers.info/img/flags/small/tn_fm-flag.gif'),
( 'Moldova', 'MD', 'https://www.worldometers.info/img/flags/small/tn_md-flag.gif'),
( 'Monaco', 'MC', 'https://www.worldometers.info/img/flags/small/tn_mn-flag.gif'),
( 'Mongolia', 'MN', 'https://www.worldometers.info/img/flags/small/tn_mg-flag.gif'),
( 'Montenegro', 'ME', 'https://www.worldometers.info/img/flags/small/tn_mj-flag.gif'),
( 'Morocco', 'MA', 'https://www.worldometers.info/img/flags/small/tn_mo-flag.gif'),
( 'Mozambique', 'MZ', 'https://www.worldometers.info/img/flags/small/tn_mz-flag.gif'),
( 'Myanmar', 'MM', 'https://www.worldometers.info/img/flags/small/tn_bm-flag.gif'),
( 'Namibia', 'NA', 'https://www.worldometers.info/img/flags/small/tn_wa-flag.gif'),
( 'Nauru', 'NR', 'https://www.worldometers.info/img/flags/small/tn_nr-flag.gif'),
( 'Nepal', 'NP', 'https://www.worldometers.info/img/flags/small/tn_np-flag.gif'),
( 'Netherlands', 'NL', 'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif'),
( 'New Zealand', 'NZ', 'https://www.worldometers.info/img/flags/small/tn_nz-flag.gif'),
( 'Nicaragua', 'NI', 'https://www.worldometers.info/img/flags/small/tn_nu-flag.gif'),
( 'Niger', 'NE', 'https://www.worldometers.info/img/flags/small/tn_ng-flag.gif'),
( 'Nigeria', 'NG', 'https://www.worldometers.info/img/flags/small/tn_ni-flag.gif'),
( 'North Macedonia', 'MK', 'https://www.worldometers.info/img/flags/small/tn_mk-flag.gif'),
( 'Norway', 'NO', 'https://www.worldometers.info/img/flags/small/tn_no-flag.gif'),
( 'Oman', 'OM', 'https://www.worldometers.info/img/flags/small/tn_mu-flag.gif'),
( 'Pakistan', 'PK', 'https://www.worldometers.info/img/flags/small/tn_pk-flag.gif'),
( 'Palau', 'PW', 'https://www.worldometers.info/img/flags/small/tn_ps-flag.gif'),
( 'Panama', 'PA', 'https://www.worldometers.info/img/flags/small/tn_pm-flag.gif'),
( 'Papua New Guinea', 'PG', 'https://www.worldometers.info/img/flags/small/tn_pp-flag.gif'),
( 'Paraguay', 'PY', 'https://www.worldometers.info/img/flags/small/tn_pa-flag.gif'),
( 'Peru', 'PE', 'https://www.worldometers.info/img/flags/small/tn_pe-flag.gif'),
( 'Philippines', 'PH', 'https://www.worldometers.info/img/flags/small/tn_rp-flag.gif'),
( 'Poland', 'PL', 'https://www.worldometers.info/img/flags/small/tn_pl-flag.gif'),
( 'Portugal', 'PT', 'https://www.worldometers.info/img/flags/small/tn_po-flag.gif'),
( 'Qatar', 'QA', 'https://www.worldometers.info/img/flags/small/tn_qa-flag.gif'),
( 'Romania', 'RO', 'https://www.worldometers.info/img/flags/small/tn_ro-flag.gif'),
( 'Russia', 'RU', 'https://www.worldometers.info/img/flags/small/tn_rs-flag.gif'),
( 'Rwanda', 'RW', 'https://www.worldometers.info/img/flags/small/tn_rw-flag.gif'),
( 'Saint Kitts and Nevis', 'KN', 'https://www.worldometers.info/img/flags/small/tn_sc-flag.gif'),
( 'Saint Lucia', 'LC', 'https://www.worldometers.info/img/flags/small/tn_st-flag.gif'),
( 'Saint Vincent and the Grenadines', 'VC', 'https://www.worldometers.info/img/flags/small/tn_vc-flag.gif'),
( 'Samoa', 'WS', 'https://www.worldometers.info/img/flags/small/tn_ws-flag.gif'),
( 'San Marino', 'SM', 'https://www.worldometers.info/img/flags/small/tn_sm-flag.gif'),
( 'Sao Tome and Principe', 'ST', 'https://www.worldometers.info/img/flags/small/tn_tp-flag.gif'),
( 'Saudi Arabia', 'SA', 'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif'),
( 'Senegal', 'SN', 'https://www.worldometers.info/img/flags/small/tn_sg-flag.gif'),
( 'Serbia', 'RS', 'https://www.worldometers.info/img/flags/small/tn_ri-flag.gif'),
( 'Seychelles', 'SC', 'https://www.worldometers.info/img/flags/small/tn_se-flag.gif'),
( 'Sierra Leone', 'SL', 'https://www.worldometers.info/img/flags/small/tn_sl-flag.gif'),
( 'Singapore', 'SG', 'https://www.worldometers.info/img/flags/small/tn_sn-flag.gif'),
( 'Slovakia', 'SK', 'https://www.worldometers.info/img/flags/small/tn_lo-flag.gif'),
( 'Slovenia', 'SI', 'https://www.worldometers.info/img/flags/small/tn_si-flag.gif'),
( 'Solomon Islands', 'SB', 'https://www.worldometers.info/img/flags/small/tn_bp-flag.gif'),
( 'Somalia', 'SO', 'https://www.worldometers.info/img/flags/small/tn_so-flag.gif'),
( 'South Africa', 'ZA', 'https://www.worldometers.info/img/flags/small/tn_sf-flag.gif'),
( 'South Sudan', 'SS', 'https://www.worldometers.info/img/flags/small/tn_od-flag.gif'),
( 'Spain', 'ES', 'https://www.worldometers.info/img/flags/small/tn_sp-flag.gif'),
( 'Sri Lanka', 'LK', 'https://www.worldometers.info/img/flags/small/tn_ce-flag.gif'),
( 'Sudan', 'SD', 'https://www.worldometers.info/img/flags/small/tn_su-flag.gif'),
( 'Suriname', 'SR', 'https://www.worldometers.info/img/flags/small/tn_ns-flag.gif'),
( 'Sweden', 'SE', 'https://www.worldometers.info/img/flags/small/tn_sw-flag.gif'),
( 'Switzerland', 'CH', 'https://www.worldometers.info/img/flags/small/tn_sz-flag.gif'),
( 'Syria', 'SY', 'https://www.worldometers.info/img/flags/small/tn_sy-flag.gif'),
( 'Taiwan', 'TW', 'https://www.worldometers.info/img/flags/small/tn_tw-flag.gif'),
( 'Tajikistan', 'TJ', 'https://www.worldometers.info/img/flags/small/tn_ti-flag.gif'),
( 'Tanzania', 'TZ', 'https://www.worldometers.info/img/flags/small/tn_tz-flag.gif'),
( 'Thailand', 'TH', 'https://www.worldometers.info/img/flags/small/tn_th-flag.gif'),
( 'Togo', 'TG', 'https://www.worldometers.info/img/flags/small/tn_to-flag.gif'),
( 'Tonga', 'TO', 'https://www.worldometers.info/img/flags/small/tn_tn-flag.gif'),
( 'Trinidad and Tobago', 'TT', 'https://www.worldometers.info/img/flags/small/tn_td-flag.gif'),
( 'Tunisia', 'TN', 'https://www.worldometers.info/img/flags/small/tn_ts-flag.gif'),
( 'Turkey', 'TR', 'https://www.worldometers.info/img/flags/small/tn_tu-flag.gif'),
( 'Turkmenistan', 'TM', 'https://www.worldometers.info/img/flags/small/tn_tx-flag.gif'),
( 'Tuvalu', 'TV', 'https://www.worldometers.info/img/flags/small/tn_tv-flag.gif'),
( 'Uganda', 'UG', 'https://www.worldometers.info/img/flags/small/tn_ug-flag.gif'),
( 'Ukraine', 'UA', 'https://www.worldometers.info/img/flags/small/tn_up-flag.gif'),
( 'United Arab Emirates', 'AE', 'https://www.worldometers.info/img/flags/small/tn_ae-flag.gif'),
( 'United Kingdom', 'GB', 'https://www.worldometers.info/img/flags/small/tn_uk-flag.gif'),
( 'United States', 'US', 'https://www.worldometers.info/img/flags/small/tn_us-flag.gif'),
( 'Uruguay', 'UY', 'https://www.worldometers.info/img/flags/small/tn_uy-flag.gif'),
( 'Uzbekistan', 'UZ', 'https://www.worldometers.info/img/flags/small/tn_uz-flag.gif'),
( 'Vanuatu', 'VU', 'https://www.worldometers.info/img/flags/small/tn_ve-flag.gif'),
( 'Vatican City', 'VA', 'https://www.worldometers.info/img/flags/small/tn_vt-flag.gif'),
( 'Venezuela', 'VE', 'https://www.worldometers.info/img/flags/small/tn_ve-flag.gif'),
( 'Vietnam', 'VN', 'https://www.worldometers.info/img/flags/small/tn_vm-flag.gif'),
( 'Yemen', 'YE', 'https://www.worldometers.info/img/flags/small/tn_ym-flag.gif'),
( 'Zambia', 'ZM', 'https://www.worldometers.info/img/flags/small/tn_za-flag.gif'),
( 'Zimbabwe', 'ZW', 'https://www.worldometers.info/img/flags/small/tn_zi-flag.gif'),
( 'Scotland', 'SCO', 'https://en.wikipedia.org/wiki/Scotland#/media/File:Flag_of_Scotland.svg'),
( 'Puerto Rico', 'PR', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg'),
( 'US Virgin Islands', 'USVI', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg');